export const FINANCE_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_PPTK: 'PENDING_PPTK',
    PENDING_REPORT: 'PENDING_REPORT',
    PENDING_EVALUATION: 'PENDING_EVALUATION',
    PENDING_BPP: 'PENDING_BPP',
    PENDING_REQUEST: 'PENDING_REQUEST',
    PENDING_KAPUS: 'PENDING_KAPUS',
    PENDING_CROSSCHECK: 'PENDING_CROSSCHECK',
    COMPLETED: 'COMPLETED'
};

export const STATUS_LABELS = {
    [FINANCE_STATUS.DRAFT]: 'Draft (Pengelola)',
    [FINANCE_STATUS.PENDING_PPTK]: 'Menunggu PPTK',
    [FINANCE_STATUS.PENDING_REPORT]: 'Proses Petugas',
    [FINANCE_STATUS.PENDING_EVALUATION]: 'Menunggu Evaluasi',
    [FINANCE_STATUS.PENDING_BPP]: 'Pengecekan BPP',
    [FINANCE_STATUS.PENDING_REQUEST]: 'Permintaan Transfer',
    [FINANCE_STATUS.PENDING_KAPUS]: 'Persetujuan Kapus',
    [FINANCE_STATUS.PENDING_CROSSCHECK]: 'Crosscheck Akhir',
    [FINANCE_STATUS.COMPLETED]: 'Selesai / Cair'
};

export const WORKFLOW_ORDER = [
    FINANCE_STATUS.DRAFT,
    FINANCE_STATUS.PENDING_PPTK,
    FINANCE_STATUS.PENDING_REPORT,
    FINANCE_STATUS.PENDING_EVALUATION,
    FINANCE_STATUS.PENDING_BPP,
    FINANCE_STATUS.PENDING_REQUEST,
    FINANCE_STATUS.PENDING_KAPUS,
    FINANCE_STATUS.PENDING_CROSSCHECK,
    FINANCE_STATUS.COMPLETED
];
